# Reemplaza estos dos valores con los tuyos reales de SonarCloud
# (los ves en sonarcloud.io -> tu proyecto -> Information, o en la URL del proyecto)
sonar.projectKey=9263999ed9b6a068074b093fdaf34ede3c8f07eb
sonar.organization=berriop

sonar.sources=src
sonar.tests=src/__tests__
sonar.exclusions=node_modules/**,dist/**,coverage/**

# Ruta al reporte de cobertura que genera vitest (npm run test:coverage)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
